### ISSUE TITLE
Error message displayed when piping into HEAD command

### ISSUE THREAD

**Issue by 0xln** [hops/pack2#14]
When running the following command 

`./pack2 statsgen plains.txt | head`

The following error message is displayed. Appears to be cosmetic. 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', src/statsgen.rs:174:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by hops** [comment]
This is a duplicated of #17 so I'll close this one.
While technically you being the first to report it I decided to track this issue in the one @roycewilliams opened.
